
Metrics/AbcSize:
  Max: 54

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/ClassLength:
  Max: 183

Metrics/MethodLength:
  Max: 81

Metrics/ModuleLength:
  Max: 119

Metrics/BlockLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120