production:
  adapter: postgresql
  encoding: unicode
  database: issues_prod
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: issues_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: issues_test
  pool: 5
